#!/bin/sh

# Pongo a disposición pública este script bajo el término de "software de dominio público".
# Puedes hacer lo que quieras con él porque es libre de verdad; no libre con condiciones como las licencias GNU y otras patrañas similares.
# Si se te llena la boca hablando de libertad entonces hazlo realmente libre.
# No tienes que aceptar ningún tipo de términos de uso o licencia para utilizarlo o modificarlo porque va sin CopyLeft.

# ----------
# Script de NiPeGun para configurar un router OpenWrt para que envíe logs a un servidor Wazuh
#
# Ejecución remota:
#   curl -sL https://raw.githubusercontent.com/nipegun/o-scripts/master/PostInst/Wazuh-Agente-Instalar,sh | sh -s [IPServWazuh]
# ----------

vIPServWazuh="$1"

# Envío mediante logd y logread
  sed -i -e "s|config system|config system\n  option log_ip '"$vIPServWazuh"'\n  option log_port '514'|g" /etc/config/system

# Reiniciar el servicio de logs
  /etc/init.d/log restart

# Luego, en el servidor Wazuh

echo '<ossec_config>'                      | sudo tee -a /var/ossec/etc/ossec.conf
echo ''                                    | sudo tee -a /var/ossec/etc/ossec.conf
echo '  <remote>'                          | sudo tee -a /var/ossec/etc/ossec.conf
echo '    <connection>syslog</connection>' | sudo tee -a /var/ossec/etc/ossec.conf
echo '    <port>514</port>'                | sudo tee -a /var/ossec/etc/ossec.conf
echo '    <protocol>udp</protocol>'        | sudo tee -a /var/ossec/etc/ossec.conf
echo '  </remote>'                         | sudo tee -a /var/ossec/etc/ossec.conf
echo ''                                    | sudo tee -a /var/ossec/etc/ossec.conf
echo '</ossec_config>'                     | sudo tee -a /var/ossec/etc/ossec.conf

sudo systemctl restart wazuh-manager
